stages:
  - build
  - test

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - cd patient-service
    - mvn -q -DskipTests package

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17
  services:
    - name: mongo:7
      alias: mongo
  variables:
    SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/patients
  script:
    - cd patient-service
    - mvn -q test
